version: '3.1'
services:
  postgresql:
    container_name: rmltc-postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: rml
      POSTGRES_USER: rml
      POSTGRES_DB: rml
    ports:
      - "5432:5432"
    